export default {
  form: document.querySelector('#header__form'),
  input: document.querySelector('.header__form'),
  movieList: document.querySelector('.movies__list'),
  spinner: document.querySelector('.spinner__cube'),
  pagination: document.querySelector('.pagination__list'),
  prevBtnRef: document.querySelector('.pagination__button-left'),
  firstBtnRef: document.querySelector('.first'),
  modal: document.querySelector('#modal'),
  modalEl: document.querySelector('.modal'),
  watchedBtn: document.querySelector('.modal__button--watched'),
  queueBtn: document.querySelector('.modal__button--queue'),
  btnIsActive: document.querySelector('.button--active'),
  btnW: document.querySelector('.header--watched-btn'),
  btnQ: document.querySelector('.header--queue-btn'),
};
